CREATE TABLE Afiliacao (
    Nome VARCHAR2(50),
    Id NUMBER,
    
    CONSTRAINT AFI_ID_PK PRIMARY KEY (ID)
);

CREATE TABLE Personagem (
    Lado_Forca VARCHAR2(50),
    Nome VARCHAR2(50),
    Bordao VARCHAR2(50),
    Id NUMBER,
     
    CONSTRAINT PERR_ID_PK PRIMARY KEY (Id)
);

CREATE TABLE Equipamento (
    Nome VARCHAR2(50),
    Id NUMBER,
    
    CONSTRAINT EQUI_Id_PK PRIMARY KEY (Id)
);

CREATE TABLE Planeta (
    Sistema VARCHAR2(50),
    Id NUMBER,
    Atmosfera VARCHAR2(50),
    Qtd_Lua NUMBER,
    Qtd_sol NUMBER,
    Setor VARCHAR2(50),
    Nome VARCHAR2(50),
    Regiao VARCHAR2(50),
    
    CONSTRAINT PLAN_ID_PK  PRIMARY KEY (ID)
);

CREATE TABLE Robotico (
    Modelo VARCHAR2(50),
    Classe VARCHAR2(50),
    Serie VARCHAR2(50),
    Cor_Lataria VARCHAR2(50),
    PER_id NUMBER,
    
    CONSTRAINT ROBO_PER_ID_PK PRIMARY KEY (PER_ID),
    CONSTRAINT ROBO_ID_FK FOREIGN KEY(PER_id) REFERENCES Personagem (Id)
);

CREATE TABLE Biologico (
    Cor_Cabelo VARCHAR2(50),
    Morte VARCHAR2(50),
    Raca VARCHAR2(50),
    Genero VARCHAR2(50),
    Cor_Pele VARCHAR2(50),
    Ocupacao VARCHAR2(50),
    Cor_Olhos VARCHAR2(50),
    PER_id NUMBER,
    
    CONSTRAINT BIOL_ID_PK PRIMARY KEY (PER_ID),
    CONSTRAINT BIOL_ID_FK FOREIGN KEY(PER_id) REFERENCES Personagem (Id)
);

CREATE TABLE Veiculo (
    Tripulacao VARCHAR2(50),
    Fabricante VARCHAR2(50),
    Id NUMBER,
    Modelo VARCHAR2(50),
    Classe VARCHAR2(50),
    Nome VARCHAR2(50),
    
    CONSTRAINT VEIC_ID_PK  PRIMARY KEY (ID)
);

CREATE TABLE Arma (
    Nome VARCHAR2(50),
    Id VARCHAR2(50) ,
    Fabricante VARCHAR2(50),
    Proposito VARCHAR2(50),
    Alcance VARCHAR2(50),
    Criador VARCHAR2(50),
    
    CONSTRAINT ArmaA_ID_PK PRIMARY KEY(ID) 
);

CREATE TABLE PER_ARM (
    PER_id NUMBER,
    ARM_id VARCHAR2(50),
    
    CONSTRAINT PER_ARM_ID_PK PRIMARY KEY(PER_id,ARM_id),
    CONSTRAINT PER_ARM_ID_FK FOREIGN KEY(PER_id) REFERENCES Personagem (Id),
    CONSTRAINT ARM_PER_ID_FK FOREIGN KEY(ARM_ID) REFERENCES Arma(ID)
);

CREATE TABLE PER_REL(
    PER_ID NUMBER,
    PER_ID2 NUMBER,
    
    CONSTRAINT PER_ID_REL_PK PRIMARY KEY (PER_ID, PER_ID2),
    CONSTRAINT PER_ID_REL_PK FOREIGN KEY (PER_ID) REFERENCES PERSONAGEM(ID),
    CONSTRAINT PER_ID2_REL_FK FOREIGN KEY (PER_ID) REFERENCES PERSONAGEM(ID)
);

CREATE TABLE ARMA_VEIC (
    ARM_id VARCHAR2(50),
    VEI_id NUMBER,
    
    CONSTRAINT ARMA_VEIC_ID_PK PRIMARY KEY(ARM_id,VEI_id),
    CONSTRAINT VEIC_ARMA_ID_FK FOREIGN KEY(VEI_id) REFERENCES Veiculo (Id),
    CONSTRAINT ARMA_VEIC_ID_FK FOREIGN KEY(ARM_ID) REFERENCES ARMA (ID)
);

CREATE TABLE VEI_AFI (
    VEI_id NUMBER,
    AFI_id NUMBER,
    
    CONSTRAINT VEI_AFI_PK PRIMARY KEY(VEI_id,AFI_id),
    CONSTRAINT VEI_AFI_FK FOREIGN KEY(VEI_id) REFERENCES Veiculo (Id),
    CONSTRAINT AFI_VEI_FK FOREIGN KEY(AFI_id) REFERENCES Afiliacao (Id)
);

CREATE TABLE PLA_AFI (
    PLA_id NUMBER,
    AFI_id NUMBER,
    
    CONSTRAINT PLA_AFI_PK PRIMARY KEY(PLA_id,AFI_id),
    CONSTRAINT PLA_AFI_FK FOREIGN KEY(PLA_id) REFERENCES Planeta (Id),
    CONSTRAINT AFI_PLA_FK FOREIGN KEY(AFI_id) REFERENCES Afiliacao (Id)
);

CREATE TABLE ROB_EQUIP (
    EQUIP_Id NUMBER,
    ROB_Id NUMBER,
    
    CONSTRAINT ROB_EQUIP_PK PRIMARY KEY(EQUIP_Id, ROB_Id),
    CONSTRAINT PER_ROB_FK FOREIGN KEY(ROB_Id) REFERENCES Robotico (PER_id),
    CONSTRAINT ROB_PER_FK FOREIGN KEY(EQUIP_Id) REFERENCES Equipamento (Id)
);

CREATE TABLE PER_AFI (
    AFI_id NUMBER,
    PER_id NUMBER,
    
    CONSTRAINT PER_AFI_PK PRIMARY KEY(AFI_id,PER_id),
    CONSTRAINT AFI_PER_FK FOREIGN KEY(AFI_id) REFERENCES Afiliacao (Id),
    CONSTRAINT PER_AFI_FK FOREIGN KEY(PER_id) REFERENCES Personagem (Id)
);

CREATE TABLE PER_VEI (
    PER_id NUMBER,
    VEI_id NUMBER,
    
    CONSTRAINT PER_VEI_PK PRIMARY KEY(PER_id,VEI_id),
    CONSTRAINT PER_VEI_FK FOREIGN KEY(PER_id) REFERENCES Personagem (Id),
    CONSTRAINT VEI_PER_FK FOREIGN KEY(VEI_id) REFERENCES Veiculo (Id)
);

CREATE TABLE PER_CRIA_ROB(
    BIO_ID NUMBER,
    ROB_ID NUMBER,
    
    CONSTRAINT BIO_ID_CRIA_PK PRIMARY KEY (BIO_ID, ROB_ID),
    CONSTRAINT BIO_ID_CRIA_FK FOREIGN KEY (BIO_ID) REFERENCES PERSONAGEM(ID),
    CONSTRAINT ROB_ID_CRIA_FK FOREIGN KEY (ROB_ID) REFERENCES PERSONAGEM(ID)
);

CREATE TABLE PER_NASCEU_PLA (
    PER_ID NUMBER,
    PLA_ID NUMBER,
    
    CONSTRAINT PER_NASCEU_PLA_PK PRIMARY KEY (PER_ID, PLA_ID),
    CONSTRAINT NASCEU_PER_FK FOREIGN KEY (PER_ID) REFERENCES PERSONAGEM(ID),
    CONSTRAINT NASCEU_PLA_FK FOREIGN KEY (PLA_ID) REFERENCES PLANETA(ID)
);    