-- 1. TODOS OS PERSONAGENS QUE TEM ALGUM TIPO DE RELACIONAMENTO
SELECT P.NOME FROM PERSONAGEM P 
INNER JOIN PER_REL PR ON PR.PER_ID = P.ID OR PR.PER_ID2 = P.ID;

-- 2. TODOS OS VEÍCULO QUE CONTÉM ARMAS
SELECT * FROM VEICULO V
INNER JOIN ARMA_VEIC AV ON AV.VEI_ID = V.ID;

-- 3. TODOS OS PERSONAGENS QUE NASCERAM EM UM PLANETA QUE SÃO DE DETERMINADA AFILIAÇÃO
SELECT P.NOME FROM PERSONAGEM P
INNER JOIN PER_NASCEU_PLA PNP ON P.ID = PNP.PER_ID
INNER JOIN PLA_AFI PA ON PNP.PLA_ID = PA.PLA_ID;

-- 4. TODOS OS PERSONAGENS QUE POSSUEM VEÍCULOS COM ARMA
SELECT P.NOME FROM PERSONAGEM P
INNER JOIN PER_VEI PV ON P.ID = PV.PER_ID
INNER JOIN ARMA_VEIC AV ON AV.VEI_ID = PV.VEI_ID;

-- 5. TODOS OS PERSONAGENS BIOLÓGICOS QUE CONSTRUIRAM UM SER ROBÓTICO
SELECT P.NOME FROM PERSONAGEM P
INNER JOIN PER_CRIA_ROB PCR ON PCR.BIO_ID = P.ID;

-- 6. TODOS OS PERSONAGENS QUE SÃO BIOLÓGICOS E SÃO DE AFILIAÇÃO "X"
SELECT P.NOME FROM PERSONAGEM P
INNER JOIN PER_BIO PB ON P.ID = PB.PER_ID
INNER JOIN PER_AFI PA ON PA.PER_ID = P.ID AND PA.AFI_ID = 1;

-- 7. TODOS OS ROBOS QUE POSSUEM EQUIPAMENTO
SELECT P.NOME FROM PERSONAGEM P
INNER JOIN ROB_EQUIP RE ON RE.ROB_ID = P.ID;

-- 8. TODOS OS PERSONAGENS BIOLÓGICOS QUE NASCERAM NO PLANETA "X"
SELECT P.NOME FROM PERSONAGEM P 
INNER JOIN PER_BIO PB ON PB.PER_ID = P.ID
INNER JOIN PER_NASCEU_PLA PNP ON P.ID = PNP.PER_ID;

-- 9. TODOS OS PERSONAGENS BIOLÓGICOS QUE POSSUEM ARMA
SELECT P.NOME FROM PERSONAGEM P 
INNER JOIN PER_BIO PB ON PB.PER_ID = P.ID
INNER JOIN PER_ARM PA ON PA.PER_ID = P.ID;

-- 10. TODOS OS PERSONAGENS BIOLÓGICOS QUE POSSUEM VEÍCULOS COM ARMAS
SELECT P.NOME FROM PERSONAGEM P 
INNER JOIN PER_BIO PB ON PB.PER_ID = P.ID
INNER JOIN PER_VEI PV ON PV.PER_ID = P.ID
INNER JOIN VEI_ARM VA ON VA.VEI_ID = PV.VEI_ID;

-- 11. TODOS OS VEÍCULOS DE "X" AFILIAÇÃO
SELECT P.NOME FROM PERSONAGEM P
INNER JOIN PER_AFI PA ON PA.PER_ID = P.ID;

-- 12. TODOS OS PERSONAGENS QUE TEM A LETRA "D" NO NOME
SELECT P.NOME FROM PERSONAGEM P WHERE P.NOME LIKE '%d%';

-- 13. TODOS OS PERSONAGENS DO LADO NEGRO DA FORÇA
SELECT P.NOME FROM PERSONAGEM P WHERE P.LADO_FORCA = LOWER('negro');

-- 14. TODOS OS PERSONAGENS DO LADO LUZ DA FORÇA
SELECT P.NOME FROM PERSONAGEM P WHERE P.LADO_FORCA = LOWER('luz');

-- 15. TODOS OS PERSONAGENS NASCIDOS EM DETERMINADO PLANETA
SELECT P.NOME FROM PERSONAGEM P 
INNER JOIN PER_NASCEU_PLA PNP ON PNP.PER_ID = P.ID;

-- 16. TODAS AS ARMAS QUE O VEÍCULO X CONTÉM
SELECT A.NOME FROM ARMA A
INNER JOIN ARMA_VEIC AV ON AV.ARM_ID = A.ID
INNER JOIN VEICULO V ON V.ID = AV.VEI_ID AND V.ID = 1;
